name: mingw-w64-gcc

# Controls when the workflow will run
on: workflow_dispatch
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with: 
          msystem: MINGW32
          update: true
          install: >-
            git
            unzip
            xz
            p7zip
            curl
            m4
            zstd
            base-devel
            gmp
            mpfr
            isl
            mpc
          
      - name: build
        id: build
        shell: msys2 {0}
        run: ./build.sh

      - name: release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build.outputs.RELEASE_NAME }}
          release_name: ${{ steps.build.outputs.RELEASE_NAME }}
          body: |
            GCC v${{ steps.build.outputs.GCC_VERSION }}
            MinGW-w64 v${{ steps.build.outputs.MINGW_VERSION }}

      - name: upload
        id: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ steps.build.outputs.OUTPUT_BINARY }}
          asset_name: ${{ steps.build.outputs.OUTPUT_NAME }}
          asset_content_type: application/x-7z-compressed
