name: mingw-w64-gcc

# Controls when the workflow will run
on: workflow_dispatch
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with: 
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            p7zip
            base-devel
            git
          

      - shell: msys2 {0}
        run: ./build.sh
